export type ReportType = "ESG_EVIDENCE" | "GREEN_LOAN" | "SOLAR_INVESTMENT";

export interface GeneratedReportResponse {
  reportType: ReportType;
  reportId: string;
  generatedAt: string;
  pdfBlob: Blob;
  pdfUrl: string;
  filename: string;
}

/**
 * Frontend Service Interface for triggering report generation from the backend API.
 * The frontend sends the selected reportType and authenticated company context to POST /reports/generate.
 */
export async function requestGenerateReport(
  companyId: string,
  reportType: ReportType,
  companyName: string = "Factory"
): Promise<GeneratedReportResponse> {
  // In production environment, calls FastAPI/backend service endpoint:
  // const response = await fetch('/api/v1/reports/generate', {
  //   method: 'POST',
  //   headers: { 'Content-Type': 'application/json' },
  //   body: JSON.stringify({ companyId, reportType }),
  // });
  // if (!response.ok) throw new Error("Backend API error generating report");
  // const pdfBlob = await response.blob();

  // Simulated backend API response producing valid PDF Blob stream
  await new Promise((resolve) => setTimeout(resolve, 1400));

  const now = new Date();
  const dateFormatted = now.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
  const dateFilename = now.toISOString().slice(0, 10);
  const safeCompanyName = companyName.replace(/[^a-zA-Z0-9]/g, "_");

  let typePrefix = "ESG_Evidence_Report";
  let titleStr = "ReMargin ESG Evidence Report";
  if (reportType === "GREEN_LOAN") {
    typePrefix = "Green_Loan_Enablement_Report";
    titleStr = "ReMargin Green Loan Enablement Report";
  } else if (reportType === "SOLAR_INVESTMENT") {
    typePrefix = "Solar_Investment_Report";
    titleStr = "ReMargin Solar Investment Report";
  }

  const filename = `${typePrefix}_${safeCompanyName}_${dateFilename}.pdf`;

  // Standard valid PDF stream returned by API
  const pdfStreamText = `%PDF-1.4
1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj
2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>> endobj
3 0 obj <</Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources <</Font <</F1 5 0 R>>>>>> endobj
4 0 obj <</Length 240>> stream
BT
/F1 18 Tf
50 720 Td
(${titleStr}) Tj
/F1 12 Tf
0 -30 Td
(Factory: ${companyName}) Tj
0 -20 Td
(Generated At: ${dateFormatted}) Tj
0 -20 Td
(Report ID: RM-${reportType.slice(0, 3)}-${Date.now().toString().slice(-6)}) Tj
0 -30 Td
(This PDF report was generated by ReMargin Backend API Service.) Tj
0 -20 Td
(Contains verified Scope 1 & 2 emissions, baseline KPIs, and evidence registers.) Tj
ET
endstream endobj
5 0 obj <</Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold>> endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000062 00000 n 
0000000117 00000 n 
0000000244 00000 n 
0000000535 00000 n 
trailer <</Size 6 /Root 1 0 R>>
startxref
610
%%EOF`;

  const pdfBlob = new Blob([pdfStreamText], { type: "application/pdf" });
  const pdfUrl = URL.createObjectURL(pdfBlob);

  return {
    reportType,
    reportId: `RM-${reportType.slice(0, 3)}-${Date.now().toString().slice(-6)}`,
    generatedAt: `${dateFormatted} at ${now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}`,
    pdfBlob,
    pdfUrl,
    filename,
  };
}
